In [1]:
import pandas as pd
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent.parent))
from src.config import DATA_DIR

In [2]:
investing_data_path = DATA_DIR / "raw" / "investing_com"

data_files_paths = {
    path.stem: path
    for path in investing_data_path.iterdir()
    if path.is_file() and path.suffix == ".csv"
}
print(data_files_paths.keys())

dict_keys(['eur_pln', 'eu_carbon_emissions_futures', 'german_power_baseload_futures', 'rotterdam_coal_futures', 'dutch_ttf_natural_gas_futures'])

# Investing.com

**Investing.com** is a global financial data platform that offers access to real-time and historical data across international exchanges and financial instruments.

## Description of data from the Investing.com platform

| Category | Data | File Name | Unit | Market Time Unit (MTU) |
|---|---|---|---|---|
| **Energy Commodities & Emissions** | Carbon Emissions (CFI2Zc1) | `carbon_emissions_futures.csv` | EUR | 1 day |
|| Rotterdam Coal (ATWMc1) | `rotterdam_coal_futures.csv` | USD | 1 day |
|| ICE Dutch TTF Natural Gas (TFMBMc1) | `dutch_ttf_natural_gas_futures` | EUR | 1 day |
|| German Power Baseload Electricity Month (DBEc1) | `german_power_baseload_futures.csv` | EUR | 1 day |
| **Foreign Exchange (FX) Rates** | EUR/PLN - Euro Polish Zloty | `eur_pln.csv` | PLN | 1 day |

## 1. Energy Commodities & Emissions

### 1.1 Carbon Emissions (CFI2Zc1)

Market price of EU carbon emission allowances. The data reflects the cost of emitting one tonne of CO2 under the EU ETS.

In [3]:
carbon_emissions = pd.read_csv(data_files_paths.get("eu_carbon_emissions_futures"))
carbon_emissions.head(10)

         Date  Price   Open   High    Low    Vol. Change %
0  09/16/2026  84.74  85.57  85.83  84.07  28.63K   -1.02%
1  09/15/2026  85.61  88.00  88.29  85.30  34.46K   -2.70%
2  09/14/2026  87.99  85.66  88.53  85.51  31.37K    2.89%
3  09/11/2026  85.52  85.77  86.66  85.00  22.52K   -0.35%
4  09/10/2026  85.82  85.50  86.22  84.97  23.56K    0.29%
5  09/09/2026  85.57  85.41  86.40  84.81  26.23K    0.18%
6  09/08/2026  85.42  84.85  86.00  84.66  20.67K    0.80%
7  09/07/2026  84.74  84.20  85.34  83.91  15.43K    0.67%
8  09/04/2026  84.18  83.49  84.91  83.28  22.75K    0.78%
9  09/03/2026  83.53  84.10  84.10  83.02  17.22K   -0.64%

### 1.2 Rotterdam Coal (ATWMc1)

Benchmark price for thermal coal traded in the Rotterdam market. The data represents the market price of coal used primarily for electricity generation.

In [4]:
rotterdam_coal = pd.read_csv(data_files_paths.get("rotterdam_coal_futures"))
rotterdam_coal.head(10)

         Date   Price    Open    High     Low   Vol. Change %
0  09/16/2026  139.05  139.05  139.05  139.05  0.01K    0.04%
1  09/15/2026  139.00  138.50  138.50  138.50  0.01K   -0.22%
2  09/14/2026  139.30  139.30  139.30  139.30  0.00K    0.18%
3  09/11/2026  139.05  139.05  139.05  139.05  0.01K   -1.21%
4  09/10/2026  140.75  140.75  140.75  140.75    NaN    0.64%
5  09/09/2026  139.85  139.85  139.85  139.85  0.03K    0.79%
6  09/08/2026  138.75  138.75  138.75  138.75  0.02K    0.73%
7  09/07/2026  137.75  140.00  140.00  140.00  0.01K   -0.36%
8  09/04/2026  138.25  136.80  138.45  136.80  0.11K    1.88%
9  09/03/2026  135.70  135.25  136.50  135.25  0.09K   -0.07%

### 1.3 Dutch TTF Natural Gas (TFMBMc1)

European benchmark price for natural gas traded at the Title Transfer Facility (TTF) in the Netherlands. The data reflects wholesale natural gas prices in Europe.

In [5]:
dutch_ttf_natural_gas = pd.read_csv(
    data_files_paths.get("dutch_ttf_natural_gas_futures")
)
dutch_ttf_natural_gas.head(10)

         Date   Price    Open    High     Low     Vol. Change %
0  09/16/2026  78.030  81.150  83.280  76.500  158.62K   -2.54%
1  09/15/2026  80.060  82.300  83.415  78.725  147.73K   -3.04%
2  09/14/2026  82.566  82.000  84.500  80.635  136.81K   -0.34%
3  09/13/2026  82.845  82.000  82.845  81.410    1.00K    4.18%
4  09/11/2026  79.520  82.540  83.045  79.255  144.31K   -3.08%
5  09/10/2026  82.047  79.090  83.060  78.170  127.56K    3.53%
6  09/09/2026  79.246  78.000  80.985  76.505  148.31K    4.49%
7  09/08/2026  75.841  73.100  77.895  73.020  122.77K    3.46%
8  09/07/2026  73.306  74.555  75.200  72.405   93.73K   -2.17%
9  09/06/2026  74.930  74.555  75.005  74.000    1.93K    4.14%

### 1.4 German Power Baseload Electricity Month (DBEc1)

European benchmark price for German baseload electricity traded in the wholesale power market. The data reflects monthly electricity prices for delivery in Germany.

In [6]:
german_power_baseload = pd.read_csv(
    data_files_paths.get("german_power_baseload_futures")
)
german_power_baseload.head(10)

         Date   Price    Open    High     Low  Vol. Change %
0  09/16/2026  151.68  151.68  151.68  151.68   NaN   -0.64%
1  09/15/2026  152.65  152.65  152.65  152.65   NaN   -1.08%
2  09/14/2026  154.31  154.31  154.31  154.31   NaN    6.29%
3  09/11/2026  145.18  145.18  145.18  145.18   NaN   -1.55%
4  09/10/2026  147.47  147.47  147.47  147.47   NaN   -1.06%
5  09/09/2026  149.05  149.05  149.05  149.05   NaN    3.13%
6  09/08/2026  144.52  144.52  144.52  144.52   NaN    5.60%
7  09/04/2026  136.85  136.85  136.85  136.85   NaN   -2.87%
8  09/03/2026  140.89  140.89  140.89  140.89   NaN   -3.06%
9  09/02/2026  145.33  145.33  145.33  145.33   NaN   -0.02%

## 2. Foreign Exchange (FX) Rates

### 2.1 EUR/PLN - Euro Polish Zloty

Foreign exchange rate representing the value of the euro in Polish zloty. The data shows how many PLN are required to purchase one EUR.

In [7]:
eur_pln_fx = pd.read_csv(data_files_paths.get("eur_pln"))
eur_pln_fx.head(10)

         Date   Price    Open    High     Low  Vol. Change %
0  09/16/2026  4.3621  4.3427  4.3667  4.3369   NaN    0.45%
1  09/15/2026  4.3427  4.3404  4.3502  4.3330   NaN    0.05%
2  09/14/2026  4.3404  4.3212  4.3518  4.3194   NaN    0.39%
3  09/11/2026  4.3236  4.3263  4.3314  4.3144   NaN   -0.06%
4  09/10/2026  4.3263  4.3148  4.3325  4.3104   NaN    0.28%
5  09/09/2026  4.3142  4.3135  4.3203  4.3075   NaN    0.01%
6  09/08/2026  4.3137  4.3099  4.3192  4.3038   NaN    0.08%
7  09/07/2026  4.3101  4.3112  4.3218  4.3040   NaN   -0.02%
8  09/04/2026  4.3109  4.3209  4.3270  4.3012   NaN   -0.23%
9  09/03/2026  4.3210  4.3299  4.3364  4.3177   NaN   -0.21%