In [1]:
from jao import JaoPublicationToolPandasClient
from dotenv import load_dotenv
import os
import pandas as pd

In [2]:
load_dotenv()
jao_api_key = os.getenv("JAO_API_KEY")

client = JaoPublicationToolPandasClient(api_key=jao_api_key)

day = pd.Timestamp("20260801", tz="Europe/Warsaw")
start = pd.Timestamp("20260701", tz="Europe/Warsaw")
end = pd.Timestamp("20260802", tz="Europe/Warsaw")

# JAO - Joint Allocation Office

The Joint Allocation Office (JAO) is a centralized service company and Europe's Single Allocation Platform that auctions cross-border electricity transmission capacity rights on behalf of transmission system operators (TSOs)

## Description of Data from the JAO API
The following table provides an overview of the main variables obtained from the JAO API. The selection and terminology are based primarily on the official [CORE DA Publication Handbook](https://publicationtool.jao.eu/PublicationHandbook/Core_PublicationTool_Handbook_v2.2.pdf)

| Data | API Method Name | Unit | Market Time Unit (MTU) |
|---|---|---|---|
| Max Net Positions | `query_minmax_np` | MW | 1 hour |
| RefProg | `query_refprog` | MW | 1 hour |
| Allocation Constraint | `query_allocationconstraint` | MW | 15 min |
| DC2F | `query_dc2f`| MW | 1 hour |

### 1. Max Net Positions

**Description:**

Minimum and maximum Core net positions in MW of each hub for each MTU of the day. These indicators are extracted from the final flow-based domain and final bilateral exchange restriction.

**Publication time:** 

10:30 am (D-1)

In [3]:
minmax_np = client.query_minmax_np(day=start)
print(minmax_np.columns)
minmax_np

Index(['minALBE', 'minALDE', 'minAT', 'minBE', 'minCZ', 'minDE', 'minHR',
       'minHU', 'minFR', 'minNL', 'minPL', 'minRO', 'minSI', 'minSK',
       'minDE_NO2_BigHub', 'minNL_NO2_NorNed', 'minDE_DK2_BigHub',
       'minDE_SE4_Baltic', 'minPL_LT_BigHub', 'minPL_SE4_SwePol',
       'minRO_BG_VH', 'minNL_DK1_COBRA', 'minDE_DK1_VH', 'maxALBE', 'maxALDE',
       'maxAT', 'maxBE', 'maxCZ', 'maxDE', 'maxHR', 'maxHU', 'maxFR', 'maxNL',
       'maxPL', 'maxRO', 'maxSI', 'maxSK', 'maxDE_NO2_BigHub',
       'maxNL_NO2_NorNed', 'maxDE_DK2_BigHub', 'maxDE_SE4_Baltic',
       'maxPL_LT_BigHub', 'maxPL_SE4_SwePol', 'maxRO_BG_VH', 'maxNL_DK1_COBRA',
       'maxDE_DK1_VH'],
      dtype='str')

,minALBE,minALDE,minAT,minBE,minCZ,minDE,minHR,minHU,minFR,minNL,...,maxSK,maxDE_NO2_BigHub,maxNL_NO2_NorNed,maxDE_DK2_BigHub,maxDE_SE4_Baltic,maxPL_LT_BigHub,maxPL_SE4_SwePol,maxRO_BG_VH,maxNL_DK1_COBRA,maxDE_DK1_VH
mtu,,,,,,,,,,,,,,,,,,,,,
2026-07-01 00:00:00+02:00,-1000,-1000,-5997,-7127,-9405,-24324,-4369,-9318,-12742,-10701,...,7382,1445,0,401,616,250,491,3021,701,3501
2026-07-01 01:00:00+02:00,-1000,-1000,-6391,-7303,-9316,-24653,-4547,-9553,-12315,-10836,...,7234,1445,0,401,616,250,491,3021,701,3501
2026-07-01 02:00:00+02:00,-1000,-1000,-6325,-7306,-9304,-24053,-5169,-9497,-12157,-10657,...,7272,1445,0,401,616,250,491,3021,701,3501
2026-07-01 03:00:00+02:00,-1000,-1000,-6880,-7370,-9149,-24115,-5263,-9280,-12285,-10863,...,7177,1445,0,401,616,250,491,3021,701,3501
2026-07-01 04:00:00+02:00,-1000,-1000,-6500,-7364,-9201,-24080,-4634,-9441,-12369,-10869,...,7168,1445,0,401,616,250,491,3021,701,3501
2026-07-01 05:00:00+02:00,-1000,-1000,-6036,-7323,-8939,-23935,-5301,-4494,-12487,-10873,...,6440,1445,0,401,616,250,491,3021,701,3501
2026-07-01 06:00:00+02:00,-1000,-1000,-5994,-7194,-9325,-23899,-5075,-4842,-13188,-10680,...,6312,1445,0,401,616,250,491,3021,701,3501
2026-07-01 07:00:00+02:00,-1000,-1000,-6025,-7110,-9321,-23949,-4839,-7637,-12233,-10745,...,7431,1445,0,401,616,250,491,3016,701,3501
2026-07-01 08:00:00+02:00,-1000,-1000,-6581,-7105,-8509,-22703,-5045,-3927,-11643,-10294,...,6706,1445,0,401,616,250,491,3016,701,3501
2026-07-01 09:00:00+02:00,-1000,-1000,-6651,-7007,-8178,-23027,-4910,-3953,-10400,-9394,...,6845,1445,0,401,616,250,491,3016,701,3501
2026-07-01 10:00:00+02:00,-1000,-1000,-6592,-6989,-8273,-24230,-5021,-4131,-10030,-8439,...,6826,1445,0,401,616,250,0,3016,701,3501
2026-07-01 11:00:00+02:00,-1000,-1000,-6488,-7004,-8112,-24314,-5157,-4354,-10134,-7895,...,6960,1445,0,401,616,250,0,3016,701,3501
2026-07-01 12:00:00+02:00,-1000,-1000,-6403,-6957,-8035,-24436,-5195,-4400,-10068,-7911,...,7026,1445,0,401,616,250,0,3016,701,3501
2026-07-01 13:00:00+02:00,-1000,-1000,-6428,-6926,-7996,-24394,-5270,-4380,-10151,-7984,...,6817,1445,0,401,616,250,0,3016,701,3501
2026-07-01 14:00:00+02:00,-1000,-1000,-6542,-6936,-8160,-24120,-5186,-3355,-10173,-8104,...,7034,1445,0,401,616,250,0,3016,701,3501
2026-07-01 15:00:00+02:00,-1000,-1000,-6225,-6787,-8244,-24607,-5259,-4412,-10025,-8457,...,7284,1445,0,401,616,250,0,3016,701,3501
2026-07-01 16:00:00+02:00,-1000,-1000,-5636,-6906,-7711,-25166,-4940,-7203,-10417,-9286,...,6782,1445,0,401,616,250,0,3016,701,3501
2026-07-01 17:00:00+02:00,-1000,-1000,-6659,-7017,-7691,-24512,-4763,-9037,-10869,-9873,...,7312,1445,0,401,616,250,0,3011,701,3501
2026-07-01 18:00:00+02:00,-1000,-1000,-6650,-6792,-7758,-23936,-4672,-8465,-11940,-10381,...,6990,1445,0,401,616,250,491,3011,701,3501
2026-07-01 19:00:00+02:00,-1000,-1000,-6902,-6937,-7930,-23954,-4768,-8544,-12695,-10480,...,7494,1445,0,401,616,250,491,3011,701,3501
2026-07-01 20:00:00+02:00,-1000,-1000,-6285,-6692,-7982,-23651,-4788,-8624,-13025,-10497,...,7393,1445,0,401,616,250,491,3011,701,3501
2026-07-01 21:00:00+02:00,-1000,-1000,-6210,-6747,-8001,-23746,-4066,-8343,-13141,-10488,...,7511,1445,0,401,616,250,491,3011,701,3501
2026-07-01 22:00:00+02:00,-1000,-1000,-6186,-6899,-8019,-23655,-3841,-8291,-12644,-10530,...,7499,1445,0,401,616,250,491,3011,701,3501
2026-07-01 23:00:00+02:00,-1000,-1000,-5590,-7054,-7948,-23671,-4869,-8486,-12850,-10575,...,7346,1445,0,401,616,250,491,3021,701,3501

In [4]:
minmax_np[[c for c in minmax_np.columns if "PL" in c]]

,minPL,minPL_LT_BigHub,minPL_SE4_SwePol,maxPL,maxPL_LT_BigHub,maxPL_SE4_SwePol
mtu,,,,,,
2026-07-01 00:00:00+02:00,-6127,-250,-491,6296,250,491
2026-07-01 01:00:00+02:00,-6154,-250,-491,6280,250,491
2026-07-01 02:00:00+02:00,-6240,-250,-491,6336,250,491
2026-07-01 03:00:00+02:00,-6269,-250,-491,6274,250,491
2026-07-01 04:00:00+02:00,-6318,-250,-491,6272,250,491
2026-07-01 05:00:00+02:00,-6237,-250,-491,6327,250,491
2026-07-01 06:00:00+02:00,-6168,-250,-491,6358,250,491
2026-07-01 07:00:00+02:00,-5909,-250,-491,6191,250,491
2026-07-01 08:00:00+02:00,-5771,-250,-491,6089,250,491
2026-07-01 09:00:00+02:00,-6292,-250,-491,5786,250,491
2026-07-01 10:00:00+02:00,-5665,-250,0,5393,250,0
2026-07-01 11:00:00+02:00,-5597,-250,0,5396,250,0
2026-07-01 12:00:00+02:00,-5490,-250,0,5540,250,0
2026-07-01 13:00:00+02:00,-5510,-250,0,5586,250,0
2026-07-01 14:00:00+02:00,-5448,-250,0,5265,250,0
2026-07-01 15:00:00+02:00,-5513,-250,0,5332,250,0
2026-07-01 16:00:00+02:00,-5256,-250,0,5548,250,0
2026-07-01 17:00:00+02:00,-5198,-250,0,5225,250,0
2026-07-01 18:00:00+02:00,-5729,-250,-491,5772,250,491
2026-07-01 19:00:00+02:00,-5840,-250,-491,5955,250,491
2026-07-01 20:00:00+02:00,-5786,-250,-491,5971,250,491
2026-07-01 21:00:00+02:00,-5820,-250,-491,5914,250,491
2026-07-01 22:00:00+02:00,-5846,-250,-491,5896,250,491
2026-07-01 23:00:00+02:00,-5929,-250,-491,5972,250,491

### 2. RefProg

**Description:**

The RefProg gives the exchange data per border that are used for merging of the European grid models including HVDC-
interconnectors within the synchronous area in MW

**Publication time:**

10:30 am (D-1)

In [5]:
refprog = client.query_refprog(d_from=start, d_to=end)
print(refprog.columns)
refprog

Index(['border_AT_CZ', 'border_AT_HU', 'border_AT_SI', 'border_BA_HR',
       'border_BE_DE', 'border_BE_NL', 'border_BE_UK', 'border_BG_TR',
       'border_CH_AT', 'border_CH_DE', 'border_CH_FR', 'border_CH_IT',
       'border_CZ_SK', 'border_DE_BE', 'border_DE_AT', 'border_DE_CZ',
       'border_DE_NL', 'border_DE_PL', 'border_DK_DK2', 'border_DK_NO1',
       'border_DK_NO2', 'border_DK_NO3', 'border_DK_NO4', 'border_DK_SE1',
       'border_DK_SE2', 'border_DK1_UK_Viking1', 'border_DK1_UK_Viking2',
       'border_ES_PT', 'border_FR_BE', 'border_FR_DE', 'border_FR_ES',
       'border_FR_IT', 'border_FR_UK', 'border_FR_UKIFA2',
       'border_FR_UKIFA20001', 'border_FR_UKIFA20002', 'border_GR_AL',
       'border_GR_BG', 'border_GR_IT', 'border_GR_MK', 'border_GR_TR',
       'border_HR_HU', 'border_HR_SI', 'border_IT_AT', 'border_IT_GR',
       'border_IT_MEMONITA1', 'border_IT_MEMONITA2', 'border_IT_SI',
       'border_ME_AL', 'border_ME_BA', 'border_ME_ITMONITA1',
       'border_ME_ITMONITA2', 'border_MK_BG', 'border_NL_UK', 'border_PL_CZ',
       'border_PL_SK', 'border_PL_UA', 'border_RO_HU', 'border_RO_MD',
       'border_RS_BA', 'border_RS_BG', 'border_RS_HR', 'border_RS_HU',
       'border_RS_ME', 'border_RS_MK', 'border_RS_RO', 'border_RS_KS',
       'border_SK_HU', 'border_UA_HU', 'border_UA_RO', 'border_UA_SK',
       'border_UA_MD', 'border_ES_MA_ESMA_link1', 'border_ES_MA_ESMA_link2',
       'border_KS_ME', 'border_SI_HU', 'border_KS_AL', 'border_MK_KS',
       'border_DE_DE_DK1_VH', 'border_DE_DK2_BigHub_DE', 'border_NL_DK1_COBRA',
       'border_RO_RO_BG_VH', 'border_NL_NL_NO2_NorNed',
       'border_DE_NO2_BigHub_DE', 'border_DE_DE_SE4_Baltic',
       'border_PL_PL_SE4_SwePol', 'border_PL_LT_BigHub_PL'],
      dtype='str')

,border_AT_CZ,border_AT_HU,border_AT_SI,border_BA_HR,border_BE_DE,border_BE_NL,border_BE_UK,border_BG_TR,border_CH_AT,border_CH_DE,...,border_MK_KS,border_DE_DE_DK1_VH,border_DE_DK2_BigHub_DE,border_NL_DK1_COBRA,border_RO_RO_BG_VH,border_NL_NL_NO2_NorNed,border_DE_NO2_BigHub_DE,border_DE_DE_SE4_Baltic,border_PL_PL_SE4_SwePol,border_PL_LT_BigHub_PL
mtu,,,,,,,,,,,,,,,,,,,,,
2026-07-01 00:00:00+02:00,-942,1066,749,241,-687,-171,-360,-100,877,2733,...,73,-1473,377,-684,-1423,0,0,0,-492,70
2026-07-01 01:00:00+02:00,-1097,917,722,100,-288,-335,-126,-100,757,2326,...,78,-1432,370,-659,-1339,0,0,0,-492,-94
2026-07-01 02:00:00+02:00,-1168,827,701,109,-304,-231,-52,-100,719,2119,...,55,-1627,420,-684,-1210,0,0,0,-492,-138
2026-07-01 03:00:00+02:00,-1131,769,674,106,-193,-285,124,-100,636,2104,...,31,-1834,385,-682,-1288,0,0,0,-492,-180
2026-07-01 04:00:00+02:00,-1080,797,650,104,-105,-281,8,-100,691,2248,...,40,-1987,-131,-684,-1280,0,0,0,-492,-174
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-01 19:00:00+02:00,-1144,1252,946,138,846,-1308,495,-199,892,868,...,320,-2969,-627,-683,-2365,0,0,0,-492,-186
2026-08-01 20:00:00+02:00,-1018,1242,869,147,884,-877,301,-200,1015,1457,...,328,-2823,-533,-684,-2369,0,0,0,-492,-184
2026-08-01 21:00:00+02:00,-1057,1249,942,83,646,-791,232,-200,787,1838,...,328,-2210,-473,-629,-2430,0,0,0,-492,-188
2026-08-01 22:00:00+02:00,-1337,1208,1028,-8,628,-713,290,-200,480,1548,...,296,-1853,-477,-412,-2332,0,0,0,-492,-192
2026-08-01 23:00:00+02:00,-1580,1152,1033,-17,634,-997,665,-200,447,684,...,309,-1157,-397,-100,-2186,0,0,0,-492,-196

In [6]:
refprog[[c for c in refprog.columns if "PL" in c]]

,border_DE_PL,border_PL_CZ,border_PL_SK,border_PL_UA,border_PL_PL_SE4_SwePol,border_PL_LT_BigHub_PL
mtu,,,,,,
2026-07-01 00:00:00+02:00,-1153,147,721,0,-492,70
2026-07-01 01:00:00+02:00,-1280,200,747,0,-492,-94
2026-07-01 02:00:00+02:00,-1273,170,707,0,-492,-138
2026-07-01 03:00:00+02:00,-1310,140,646,0,-492,-180
2026-07-01 04:00:00+02:00,-1306,119,637,0,-492,-174
...,...,...,...,...,...,...
2026-08-01 19:00:00+02:00,1223,-649,174,0,-492,-186
2026-08-01 20:00:00+02:00,1049,-801,15,0,-492,-184
2026-08-01 21:00:00+02:00,824,-742,89,0,-492,-188
2026-08-01 22:00:00+02:00,537,-425,388,0,-492,-192
2026-08-01 23:00:00+02:00,37,-112,667,0,-492,-196

### 3. Allocation Constraints 

**Description:**

As per the Core CCM, Belgium, Poland and the Netherlands are allowed to use external constraints.

**Publication time:**

10:30 am (D-1)

In [7]:
allocationconstraints = client.query_allocationconstraint(d_from=start, d_to=end)
allocationconstraints

                          BE_import  PL_import BE_export  PL_export
mtu
2026-07-01 00:00:00+02:00      None       4491      None       1772
2026-07-01 00:15:00+02:00      None       4277      None       2024
2026-07-01 00:30:00+02:00      None       4130      None       2206
2026-07-01 00:45:00+02:00      None       3932      None       2446
2026-07-01 01:00:00+02:00      None       3885      None       2525
...                             ...        ...       ...        ...
2026-08-01 22:45:00+02:00      None       4560      None       1663
2026-08-01 23:00:00+02:00      None       4222      None       2049
2026-08-01 23:15:00+02:00      None       3865      None       2451
2026-08-01 23:30:00+02:00      None       3568      None       2787
2026-08-01 23:45:00+02:00      None       3326      None       3063

[3072 rows x 4 columns]

### 4. DC2F

**Description:**

Publishes the aggregated assumptions from the grid models for each MTU on TSU and Hub level: Vertical load, generation(production) and net position for each Core hub and TSO if it differs from the hub level
- “Vertical load” is the load as seen from the transmission grid in MW in the Common Grid Model
- “Generation” is the generation in MW in the Common Grid Model
- “Core net position” is the forecast of the overall balance of the countries in MW in the Common Grid Model

**Publication time:**

10:30 am (D-1)

In [8]:
dc2f = client.query_d2cf(d_from=start, d_to=end)
print(dc2f.columns)
dc2f

Index(['verticalLoad_AT', 'verticalLoad_BE', 'verticalLoad_CZ',
       'verticalLoad_DE', 'verticalLoad_FR', 'verticalLoad_HR',
       'verticalLoad_HU', 'verticalLoad_NL', 'verticalLoad_PL',
       'verticalLoad_RO', 'verticalLoad_SI', 'verticalLoad_SK',
       'generation_AT', 'generation_BE', 'generation_CZ', 'generation_DE',
       'generation_FR', 'generation_HR', 'generation_HU', 'generation_NL',
       'generation_PL', 'generation_RO', 'generation_SI', 'generation_SK',
       'coreNetPosition_AT', 'coreNetPosition_BE', 'coreNetPosition_CZ',
       'coreNetPosition_DE', 'coreNetPosition_FR', 'coreNetPosition_HR',
       'coreNetPosition_HU', 'coreNetPosition_NL', 'coreNetPosition_PL',
       'coreNetPosition_RO', 'coreNetPosition_SI', 'coreNetPosition_SK',
       'verticalLoad_50Hertz', 'verticalLoad_Amprion', 'verticalLoad_Creos',
       'verticalLoad_TennetGmbh', 'verticalLoad_Transnet',
       'generation_50Hertz', 'generation_Amprion', 'generation_Creos',
       'generation_TennetGmbh', 'generation_Transnet',
       'coreNetPosition_50Hertz', 'coreNetPosition_Amprion',
       'coreNetPosition_Creos', 'coreNetPosition_TennetGmbh',
       'coreNetPosition_Transnet'],
      dtype='str')

,verticalLoad_AT,verticalLoad_BE,verticalLoad_CZ,verticalLoad_DE,verticalLoad_FR,verticalLoad_HR,verticalLoad_HU,verticalLoad_NL,verticalLoad_PL,verticalLoad_RO,...,generation_50Hertz,generation_Amprion,generation_Creos,generation_TennetGmbh,generation_Transnet,coreNetPosition_50Hertz,coreNetPosition_Amprion,coreNetPosition_Creos,coreNetPosition_TennetGmbh,coreNetPosition_Transnet
mtu,,,,,,,,,,,,,,,,,,,,,
2026-07-01 00:00:00+02:00,6066,6678,5602,25720,36151,2267,5293,9277,17462,5795,...,4406,8320,0,1760,1562,389,-3795,-431,-3971,-3071
2026-07-01 01:00:00+02:00,5734,6384,5449,24928,34045,1863,4952,9155,16832,5620,...,3750,8300,0,1861,1299,-278,-3348,-405,-3508,-2975
2026-07-01 02:00:00+02:00,5892,6302,5297,24826,32374,1775,4911,9616,16852,5601,...,3718,8436,0,2028,1122,-183,-3356,-392,-3546,-2853
2026-07-01 03:00:00+02:00,5306,6439,5268,25961,30758,1759,4776,9592,16270,5620,...,3819,8718,0,2296,1225,-143,-3254,-388,-3946,-2863
2026-07-01 04:00:00+02:00,5532,6483,5356,27278,30330,1741,4817,9441,16043,5686,...,4256,8637,0,2215,1268,292,-3863,-397,-4430,-3123
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-08-01 19:00:00+02:00,5955,5409,4449,21750,33076,2668,5938,4643,15481,6601,...,6177,5013,0,2156,2031,3407,-2556,-357,-3814,-2382
2026-08-01 20:00:00+02:00,5824,6171,4350,24012,33832,2638,5904,6076,16672,6637,...,6332,4946,0,1941,2380,3040,-3034,-407,-4565,-2714
2026-08-01 21:00:00+02:00,5636,6306,4236,23581,32657,2553,5885,5895,16709,6287,...,6325,5130,0,1764,2158,2742,-3100,-420,-4249,-2668
2026-08-01 22:00:00+02:00,5638,5950,4412,23164,33354,2407,5837,5802,16019,5698,...,6592,5387,0,1709,2119,3066,-2531,-422,-4382,-2560
2026-08-01 23:00:00+02:00,5164,5431,3851,21179,32154,2194,5617,5500,14675,5372,...,6600,5379,0,1675,2141,3105,-1961,-399,-3178,-2429

In [9]:
dc2f[[c for c in dc2f.columns if "PL" in c]]

                           verticalLoad_PL  generation_PL  coreNetPosition_PL
mtu
2026-07-01 00:00:00+02:00            17462          19308                2030
2026-07-01 01:00:00+02:00            16832          18691                2236
2026-07-01 02:00:00+02:00            16852          18588                2161
2026-07-01 03:00:00+02:00            16270          17887                2108
2026-07-01 04:00:00+02:00            16043          17629                2073
...                                    ...            ...                 ...
2026-08-01 19:00:00+02:00            15481          13326               -1695
2026-08-01 20:00:00+02:00            16672          14380               -1834
2026-08-01 21:00:00+02:00            16709          14758               -1477
2026-08-01 22:00:00+02:00            16019          14960                -574
2026-08-01 23:00:00+02:00            14675          14710                 519

[768 rows x 3 columns]