In [1]:
import pandas as pd
import sys
from pathlib import Path

sys.path.append(str(Path.cwd().parent))
from src.config import DATA_DIR

In [2]:
investing_data_path = DATA_DIR / "investing_com"

data_files_paths = {
    path.stem: path
    for path in investing_data_path.iterdir()
    if path.is_file() and path.suffix == ".csv"
}
print(data_files_paths.keys())

dict_keys(['eur_czk', 'eur_pln', 'brent_oil_futures', 'rotterdam_coal_futures', 'dutch_ttf_natural_gas_futures', 'carbon_emissions_futures', 'eur_usd'])

# Investing.com

**Investing.com** is a global financial data platform that offers access to real-time and historical data across international exchanges and financial instruments.

## Description of data from the Investing.com platform

| Category | Data | File Name | Unit | Market Time Unit (MTU) |
|---|---|---|---|---|
| **Energy Commodities & Emissions** | Brent Oil (LCOc1) | `brent_oil_futures.csv` | USD | 1 day |
|| Carbon Emissions (CFI2Z6) | `carbon_emissions_futures.csv` | EUR | 1 day |
|| Rotterdam Coal (ATWMc1) | `rotterdam_coal_futures.csv` | USD | 1 day |
|| ICE Dutch TTF Natural Gas (TFMBMc1) | `dutch_ttf_natural_gas_futures` | EUR | 1 day
| **Foreign Exchange (FX) Rates** | EUR/PLN - Euro Polish Zloty | `eur_pln.csv` | PLN | 1 day |
|| EUR/CZK - Euro Czech Koruna | `eur_czk.csv` | CZK | 1 day |
|| EUR/USD - Euro US Dollar | `eur_usd.csv` | USD | 1 day |

## 1. Energy Commodities & Emissions

### 1.1 Brent Oil (LCOc1)

International benchmark price for crude oil. Data represents the market price of Brent crude oil.

In [3]:
brent_oil = pd.read_csv(data_files_paths.get("brent_oil_futures"))
brent_oil.head(10)

         Date  Price   Open   High    Low     Vol. Change %
0  09/03/2026  95.81  95.19  97.62  94.02  392.46K    0.45%
1  09/02/2026  95.38  95.24  96.99  93.52  346.01K    0.77%
2  09/01/2026  94.65  90.81  95.45  90.70  425.10K    4.60%
3  08/31/2026  90.49  89.45  91.52  89.03  233.39K    2.71%
4  08/28/2026  88.10  88.51  88.75  87.26  291.89K   -0.44%
5  08/27/2026  88.49  86.06  89.13  85.01  123.41K    2.15%
6  08/26/2026  86.63  85.83  88.50  84.20  170.15K   -0.73%
7  08/25/2026  87.27  90.49  91.29  85.00  465.68K   -3.61%
8  08/24/2026  90.54  91.90  92.06  90.17  261.02K   -2.30%
9  08/21/2026  92.67  91.38  92.98  91.15  282.16K    0.76%

### 1.2 Carbon Emissions (CFI2Z6)

Market price of EU carbon emission allowances. The data reflects the cost of emitting one tonne of CO2 under the EU ETS.

In [4]:
carbon_emissions = pd.read_csv(data_files_paths.get("carbon_emissions_futures"))
carbon_emissions.head(10)

         Date  Price   Open   High    Low    Vol. Change %
0  09/03/2026  83.42  83.96  84.04  83.02  14.67K   -0.71%
1  09/02/2026  84.02  83.38  84.49  82.74  18.87K    0.82%
2  09/01/2026  83.34  83.08  83.55  81.89  23.80K    0.29%
3  08/31/2026  83.10  82.78  83.39  81.86  15.21K    0.45%
4  08/28/2026  82.73  82.42  83.10  82.31  10.29K    0.38%
5  08/27/2026  82.42  82.84  83.00  82.00  14.07K   -0.31%
6  08/26/2026  82.68  84.50  84.72  82.41  17.35K   -2.06%
7  08/25/2026  84.42  83.70  84.69  83.60  14.48K    0.74%
8  08/24/2026  83.80  82.60  84.43  82.26  18.42K    1.44%
9  08/21/2026  82.61  82.21  83.75  82.10  17.15K    0.19%

### 1.3 Rotterdam Coal (ATWMc1)

Benchmark price for thermal coal traded in the Rotterdam market. The data represents the market price of coal used primarily for electricity generation.

In [5]:
rotterdam_coal = pd.read_csv(data_files_paths.get("rotterdam_coal_futures"))
rotterdam_coal.head(10)

         Date   Price    Open    High     Low   Vol. Change %
0  09/03/2026  136.50  135.25  136.50  135.25  0.04K    0.18%
1  09/02/2026  136.25  135.95  137.00  135.00  0.02K    0.59%
2  09/01/2026  135.45  133.95  135.55  133.95  0.03K    1.23%
3  08/31/2026  133.80  133.25  133.25  133.25  0.00K    6.53%
4  08/28/2026  125.60  125.60  125.60  125.60    NaN    0.80%
5  08/27/2026  124.60  124.60  124.60  124.60    NaN    0.32%
6  08/26/2026  124.20  124.20  124.20  124.20    NaN   -0.48%
7  08/25/2026  124.80  124.80  124.80  124.80  0.00K    0.24%
8  08/24/2026  124.50  124.55  124.55  124.55  0.00K   -0.04%
9  08/21/2026  124.55  125.25  125.25  125.25  0.01K    0.65%

### 1.4 Dutch TTF Natural Gas (TFMBMc1)

European benchmark price for natural gas traded at the Title Transfer Facility (TTF) in the Netherlands. The data reflects wholesale natural gas prices in Europe.

In [6]:
dutch_ttf_natural_gas = pd.read_csv(
    data_files_paths.get("dutch_ttf_natural_gas_futures")
)
dutch_ttf_natural_gas.head(10)

         Date   Price    Open    High     Low     Vol. Change %
0  09/03/2026  71.375  73.475  74.200  70.800   97.21K   -2.77%
1  09/02/2026  73.410  73.475  75.325  71.830    0.04K    1.65%
2  09/01/2026  72.218  70.160  74.400  69.685  108.09K    3.45%
3  08/31/2026  69.809  68.350  70.715  68.005   59.72K    2.03%
4  08/30/2026  68.420  68.350  68.755  68.005    1.79K    2.15%
5  08/28/2026  66.979  68.995  70.085  66.010  128.90K   -1.64%
6  08/27/2026  68.095  66.000  68.500  65.020   43.55K    3.76%
7  08/26/2026  65.626  65.000  66.590  62.080  114.36K   -1.44%
8  08/25/2026  66.588  68.310  69.380  63.840  136.84K   -2.54%
9  08/24/2026  68.320  66.260  69.220  65.220  108.95K    3.66%

## 2. Foreign Exchange (FX) Rates

### 2.1 EUR/PLN - Euro Polish Zloty

Foreign exchange rate representing the value of the euro in Polish zloty. The data shows how many PLN are required to purchase one EUR.

In [7]:
eur_pln_fx = pd.read_csv(data_files_paths.get("eur_pln"))
eur_pln_fx.head(10)

         Date   Price    Open    High     Low  Vol. Change %
0  09/03/2026  4.3200  4.3265  4.3326  4.3191   NaN   -0.23%
1  09/02/2026  4.3298  4.3346  4.3423  4.3233   NaN   -0.15%
2  09/01/2026  4.3364  4.3303  4.3413  4.3209   NaN    0.14%
3  08/31/2026  4.3303  4.3429  4.3500  4.3248   NaN   -0.29%
4  08/28/2026  4.3431  4.3354  4.3471  4.3266   NaN    0.18%
5  08/27/2026  4.3354  4.3108  4.3413  4.3051   NaN    0.57%
6  08/26/2026  4.3108  4.3026  4.3173  4.2922   NaN    0.20%
7  08/25/2026  4.3022  4.3064  4.3131  4.2989   NaN   -0.10%
8  08/24/2026  4.3063  4.3131  4.3207  4.3022   NaN   -0.14%
9  08/21/2026  4.3125  4.3186  4.3227  4.3066   NaN   -0.14%

### 2.2 EUR/CZK - Euro Czech Koruna

Foreign exchange rate representing the value of the euro in Czech koruna. The data shows how many CZK are required to purchase one EUR.

In [8]:
eur_czk_fx = pd.read_csv(data_files_paths.get("eur_czk"))
eur_czk_fx.head(10)

         Date    Price     Open     High      Low  Vol. Change %
0  09/03/2026  24.1691  24.1710  24.2250  24.1625   NaN   -0.06%
1  09/02/2026  24.1840  24.2085  24.2585  24.1650   NaN   -0.11%
2  09/01/2026  24.2095  24.1575  24.2280  24.1230   NaN    0.22%
3  08/31/2026  24.1575  24.1410  24.1785  24.1010   NaN    0.06%
4  08/28/2026  24.1420  24.1430  24.1745  24.1000   NaN   -0.01%
5  08/27/2026  24.1435  24.1240  24.1700  24.0990   NaN    0.09%
6  08/26/2026  24.1210  24.0765  24.1510  24.0540   NaN    0.19%
7  08/25/2026  24.0745  24.0950  24.1315  24.0595   NaN   -0.09%
8  08/24/2026  24.0960  24.1070  24.1490  24.0775   NaN   -0.06%
9  08/21/2026  24.1115  24.1735  24.1785  24.0940   NaN   -0.26%

### 2.3 EUR/USD - Euro US Dollar

Foreign exchange rate representing the value of the euro in US dollars. The data shows how many USD are required to purchase one EUR.

In [9]:
eur_usd_fx = pd.read_csv(data_files_paths.get("eur_usd"))
eur_usd_fx.head(10)

         Date   Price    Open    High     Low  Vol. Change %
0  09/03/2026  1.1626  1.1585  1.1641  1.1584   NaN    0.35%
1  09/02/2026  1.1585  1.1593  1.1609  1.1566   NaN   -0.07%
2  09/01/2026  1.1593  1.1618  1.1625  1.1584   NaN   -0.22%
3  08/31/2026  1.1618  1.1585  1.1621  1.1576   NaN    0.28%
4  08/28/2026  1.1585  1.1652  1.1659  1.1578   NaN   -0.58%
5  08/27/2026  1.1652  1.1651  1.1660  1.1637   NaN    0.01%
6  08/26/2026  1.1651  1.1675  1.1678  1.1642   NaN   -0.21%
7  08/25/2026  1.1675  1.1663  1.1680  1.1651   NaN    0.09%
8  08/24/2026  1.1664  1.1679  1.1688  1.1656   NaN   -0.13%
9  08/21/2026  1.1679  1.1678  1.1712  1.1669   NaN    0.00%